flags: {}
resolver: lts-11.22
packages:
- '.'
- location: https://github.com/timbod7/adl/archive/8844fc2346f606e912d56d44a177e3fb5ca0d59d.zip
  subdirs:
  - haskell/utils
  - haskell/runtime
  - haskell/compiler-lib
  - haskell/compiler
  extra-dep: true
extra-deps:
  - amazonka-1.6.1
  - amazonka-core-1.6.1
  - amazonka-ecr-1.6.1
  - amazonka-route53-1.6.1
  - amazonka-s3-1.6.1
  - amazonka-secretsmanager-1.6.1
extra-package-dbs: []
nix:
   packages: [zlib, bzip2]
